# Alternating list

**Goal**: Write a function which takes input `n` and as output returns the length `n` list `[3,8,3,8,...]`.

## Writing a function that returns a constant list

**Preliminary Goal**: Write a function which takes input `n` and as output returns the length `n` list `[3,3,3,...]`.

In [1]:
def f(n):
    mylist = []
    for i in range(n):
        mylist.append(3)

In [2]:
f(5)

In [3]:
def f(n):
    mylist = []
    for i in range(n):
        mylist.append(3)
        return mylist

In [4]:
f(5)

[3]

In [5]:
def f(n):
    mylist = []
    for i in range(n):
        mylist.append(3)
    return mylist

In [6]:
f(5)

[3, 3, 3, 3, 3]

In [7]:
f(6)

[3, 3, 3, 3, 3, 3]

In [8]:
n

NameError: name 'n' is not defined

In [9]:
n = 100

In [10]:
f(4)

[3, 3, 3, 3]

In [11]:
n

100

## First version of the alternating function

In [1]:
def const(n):
    mylist = []
    for i in range(n):
        mylist.append(3)
    return mylist

In [2]:
const(5)

[3, 3, 3, 3, 3]

In [3]:
def alt1(n):
    mylist = const(n)
    return mylist

In [4]:
alt1(4)

[3, 3, 3, 3]

In [2]:
def alt1(n):
    mylist = const(n)
    for i in range(1,n,2):
        mylist[i] = 8
    return mylist

In [3]:
alt1(10)

[3, 8, 3, 8, 3, 8, 3, 8, 3, 8]

In [7]:
alt1(11)

[3, 8, 3, 8, 3, 8, 3, 8, 3, 8, 3]

## Checking if the index is even or odd

In [1]:
i = 7

In [2]:
i%2

1

In [3]:
6%2

0

In [4]:
def alt2(n):
    mylist = []
    for i in range(n):
        if i%2 == 0:
            mylist.append(3)
        else:
            mylist.append(8)
    return mylist

In [5]:
alt2(5)

[3, 8, 3, 8, 3]

In [6]:
alt2(6)

[3, 8, 3, 8, 3, 8]

In [4]:
def alt2(n):
    mylist = []
    for i in range(n):
        if i%2 == 0:
            mylist.append(3)
        elif i%2 == 1:
            mylist.append(8)
    return mylist

In [11]:
alt2(5)

[3, 8, 3, 8, 3]

In [12]:
alt2(6)

[3, 8, 3, 8, 3, 8]

## Using NumPy

In [8]:
import numpy as np

In [3]:
A = np.zeros((3,5))

In [4]:
type(A)

numpy.ndarray

In [5]:
A

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
A.shape

(3, 5)

In [7]:
def alt3(n):
    A = np.zeros(n)
    return A

In [9]:
alt3(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [10]:
alt3(7)[0]

0.0

In [11]:
type(alt3(7)[0])

numpy.float64

In [12]:
A = alt3(7)

In [13]:
A.dtype

dtype('float64')

In [15]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
   

In [16]:
def alt3(n):
    A = np.zeros(n, dtype=np.int64)
    return A

In [17]:
alt3(8)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
A = alt3(8)

In [20]:
A

array([0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
A+3

array([3, 3, 3, 3, 3, 3, 3, 3])

In [22]:
mylist = [0,0,0]

In [23]:
mylist+3

TypeError: can only concatenate list (not "int") to list

In [24]:
def alt3(n):
    A = np.zeros(n, dtype=np.int64)+3
    return A

In [26]:
A = alt3(5)

In [27]:
A

array([3, 3, 3, 3, 3])

In [28]:
A[1::2]

array([3, 3])

In [29]:
A[1::2] = 8

In [30]:
A

array([3, 8, 3, 8, 3])

In [6]:
def alt3(n):
    A = np.zeros(n, dtype=np.int64)+3
    A[1::2] = 8
    return A

In [32]:
alt3(5)

array([3, 8, 3, 8, 3])

In [33]:
alt3(6)

array([3, 8, 3, 8, 3, 8])

In [34]:
mylist = [3,1,4,1,5,9]

In [35]:
mylist[::2]

[3, 4, 5]

In [36]:
mylist[::2] = -17

TypeError: must assign iterable to extended slice

In [37]:
myarray = np.array(mylist)

In [38]:
myarray[::2] = -17

In [39]:
myarray

array([-17,   1, -17,   1, -17,   9])

In [40]:
mylist[::2] = [-17, -17, -17]

In [41]:
mylist

[-17, 1, -17, 1, -17, 9]

In [42]:
mylist[::2] = [-17, -17]

ValueError: attempt to assign sequence of size 2 to extended slice of size 3

In [43]:
mylist[::2] = [-17, -17, -17, -17]

ValueError: attempt to assign sequence of size 4 to extended slice of size 3

## Timing different strategies

In [1]:
def alt3(n):
    A = np.zeros(n, dtype=np.int64)+3
    A[1::2] = 8
    return A

In [2]:
alt3(10)

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [4]:
def alt3(n):
    A = np.zeros(n, dtype=np.int64)+3
    A[1::2] = 8
    return A

In [5]:
alt3(10)

array([3, 8, 3, 8, 3, 8, 3, 8, 3, 8])

In [6]:
def alt4(n):
    mylist = []
    for i in range(n):
        mylist.append(3)
    for i in range(1,n,2):
        mylist[i] = 8
    return mylist

In [7]:
alt4(10)

[3, 8, 3, 8, 3, 8, 3, 8, 3, 8]

In [8]:
%%timeit
alt4(10)

1.18 µs ± 21.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [9]:
import time

In [10]:
time.time()

1657444015.338846

In [11]:
time.time()

1657444029.606127

In [12]:
start = time.time()
alt4(10**3)
end = time.time()
t = end-start

In [13]:
t

0.0003650188446044922

In [14]:
t = 0
n = 100
while t < 5:
    n = n*2 # n *= 2
    start = time.time()
    alt4(n)
    end = time.time()
    t = end-start

In [15]:
t

5.250777959823608

In [16]:
n

52428800

In [17]:
def alt3(n):
    A = np.zeros(n, dtype=np.int64)+3
    A[1::2] = 8
    return A

In [18]:
print(n)
start = time.time()
alt3(n)
end = time.time()
t = end-start
print(t)

52428800
0.26982712745666504


In [19]:
def alt3b(n):
    A = np.zeros(n, dtype=np.int64)+3
    A[1::2] = 8
    return list(A)

In [20]:
alt3b(10)

[3, 8, 3, 8, 3, 8, 3, 8, 3, 8]

In [21]:
print(n)
start = time.time()
alt3b(n)
end = time.time()
t = end-start
print(t)

52428800
4.124554872512817


In [22]:
def alt3c(n):
    A = np.zeros(n, dtype=np.int64)+3
    for i in range(1,n,2):
        A[i] = 8
    return A

In [23]:
print(n)
start = time.time()
alt3c(n)
end = time.time()
t = end-start
print(t)

52428800
2.886206865310669
